# Generated by Django 5.2.16 on 2026-07-24 18:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_membership_unique_mysql'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True, validators=[django.core.validators.RegexValidator(message='Codes may contain only uppercase letters and numbers.', regex='^[A-Z0-9]+$')])),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_terminal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Codes may contain only uppercase letters and numbers.', regex='^[A-Z0-9]+$')])),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(editable=False, max_length=80, unique=True)),
                ('organization_code', models.CharField(default='BS', max_length=12, validators=[django.core.validators.RegexValidator(message='Codes may contain only uppercase letters and numbers.', regex='^[A-Z0-9]+$')])),
                ('unique_hex', models.CharField(editable=False, max_length=4, validators=[django.core.validators.RegexValidator(message='Asset unique suffix must be exactly four hexadecimal characters.', regex='^[0-9A-F]{4}$')])),
                ('ownership', models.CharField(choices=[('COMPANY', 'Company'), ('MANAGED_PERSONAL', 'Managed personal')], default='COMPANY', max_length=24)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('retired_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
                ('current_custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets_in_custody', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='departments.department')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='bam.assetstatus')),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='bam.assettype')),
            ],
            options={
                'ordering': ['asset_id'],
            },
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('REGISTERED', 'Registered'), ('UPDATED', 'Updated'), ('STATUS_CHANGED', 'Status changed'), ('CUSTODY_ASSIGNED', 'Custody assigned'), ('CUSTODY_RETURNED', 'Custody returned'), ('EVIDENCE_ADDED', 'Evidence added')], max_length=32)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_events', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='bam.asset')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ASSET_PHOTO', 'Asset photo'), ('SERIAL', 'Serial evidence'), ('RECEIPT', 'Receipt / proof of purchase'), ('WARRANTY', 'Warranty'), ('INSPECTION', 'Inspection evidence'), ('OTHER', 'Other')], default='OTHER', max_length=24)),
                ('file', models.FileField(upload_to='bam/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='bam.asset')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_evidence_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetCustody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_history', to='bam.asset')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_custody_assignments', to=settings.AUTH_USER_MODEL)),
                ('custodian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_custody_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('returned_at__isnull', True), ('returned_at__gte', models.F('assigned_at')), _connector='OR'), name='custody_return_not_before_assignment')],
            },
        ),
        migrations.CreateModel(
            name='AssetRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('COMPONENT_OF', 'Component of'), ('ACCESSORY_TO', 'Accessory to'), ('REPLACES', 'Replaces'), ('RELATED', 'Related')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_relationships', to='bam.asset')),
                ('parent_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_relationships', to='bam.asset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('parent_asset', 'child_asset', 'relationship_type'), name='unique_asset_relationship'), models.CheckConstraint(condition=models.Q(('parent_asset', models.F('child_asset')), _negated=True), name='asset_relationship_not_self')],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['department', 'status'], name='bam_asset_departm_95331a_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type', 'status'], name='bam_asset_asset_t_6802c0_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='bam_asset_serial__75c28b_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('organization_code', 'department', 'asset_type', 'unique_hex'), name='unique_asset_namespace_suffix'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('retired_at__isnull', True), ('acquired_at__isnull', True), ('retired_at__gte', models.F('acquired_at')), _connector='OR'), name='asset_retired_not_before_acquired'),
        ),
    ]
